composeSuccess:
  stylesheets:
    - http://yui.yahooapis.com/2.7.0/build/autocomplete/assets/skins/sam/autocomplete.css
    - /sfSocialPlugin/css/sfsac
  javascripts:
    - http://yui.yahooapis.com/2.7.0/build/yahoo-dom-event/yahoo-dom-event.js
    - http://yui.yahooapis.com/2.7.0/build/datasource/datasource-min.js
    - http://yui.yahooapis.com/2.7.0/build/connection/connection-min.js
    - http://yui.yahooapis.com/2.7.0/build/autocomplete/autocomplete-min.js
    - /sfSocialPlugin/js/sfsac
    - /message