# messages

sf_social_message_sentlist:
  url:   /messages/sent/*
  param: { module: sfSocialMessage, action: sentlist }

sf_social_message_list:
  url:   /messages/*
  param: { module: sfSocialMessage, action: list }

sf_social_message_sentread:
  url:   /message/sent/:id
  param: { module: sfSocialMessage, action: sentread }
  requirements: { id: \d+ }

sf_social_message_read:
  url:   /message/:id
  param: { module: sfSocialMessage, action: read }
  requirements: { id: \d+ }

sf_social_message_new:
  url:   /message/compose/*
  param: { module: sfSocialMessage, action: compose }

# events

sf_social_event_invitedlist:
  url:   /events/invited/*
  param: { module: sfSocialEvent, action: invitedlist }

sf_social_event_list:
  url:   /events/*
  param: { module: sfSocialEvent, action: list }

sf_social_event_pastlist:
  url:   /pastevents/*
  param: { module: sfSocialEvent, action: pastlist }

sf_social_event_edit:
  url:   /event/:id/edit
  param: { module: sfSocialEvent, action: edit }
  requirements: { id: \d+ }

sf_social_event_invite:
  url:   /event/:id/invite/*
  param: { module: sfSocialEvent, action: invite }
  requirements: { id: \d+ }

sf_social_event:
  url:   /event/:id
  param: { module: sfSocialEvent, action: view }
  requirements: { id: \d+ }

sf_social_event_new:
  url:   /event/create
  param: { module: sfSocialEvent, action: create }

# contacts

sf_social_contact_requests:
  url:   /contacts/requests/*
  param: { module: sfSocialContact, action: requests }

sf_social_contact_list:
  url:   /contacts/*
  param: { module: sfSocialContact, action: list }

sf_social_contact_accept_request:
  url:   /request/accept/:id
  param: { module: sfSocialContact, action: acceptrequest }
  requirements: { id: \d+ }

sf_social_contact_deny_request:
  url:   /request/deny/:id
  param: { module: sfSocialContact, action: denyrequest }
  requirements: { id: \d+ }

sf_social_contact_send_request:
  url:   /request/send
  param: { module: sfSocialContact, action: sendrequest }

sf_social_contact_delete:
  url:   /contact/delete/:id
  param: { module: sfSocialContact, action: delete }
  requirements: { id: \d+ }

# notify

sf_social_notify:
  url:   /notify/:id
  param: { module: sfSocialNotify, action: get }
  requirements: { id: \d+ }

# user

sf_social_user:
  url:   /user/:username
  param: { module: sfSocialUser, action: user }
  requirements: { usernam: \w+ }