viewSuccess:
  stylesheets:
    - /sfSocialPlugin/css/sfsac
    - /sfSocialPlugin/css/jquery-ac
  javascripts:
    - /sfSocialPlugin/js/jquery
    - /sfSocialPlugin/js/jquery-ac
    - /sfSocialPlugin/js/sfsac
    - /sfSocialPlugin/js/sfsgrp